### ISSUE TITLE
Ask for the change of compute acceleration

### ISSUE THREAD

**Issue by HANCKH** [legubiao/ocs2_ros2#4]
I noticed that this project is forked from **zhengxiang94/ocs2_ros2:ros2**. However, when I ran the original repository on my machine (Ubuntu 22.04 with ROS 2 Humble), it performed very slowly and consistently produced the warning:

**WARNING: The solution time window might be shorter than the MPC delay!**

In contrast, when using your forked repository, it works smoothly and performs similarly to the OCS2 ROS 1 edition. Could you clarify what modifications you made to address this issue?

Thank you for your response!

**Comment by legubiao** [comment]
I add `set(CMAKE_BUILD_TYPE Release)` in the `CmakeList.txt`.

**Comment by HANCKH** [comment]
thx!
